apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: techbank-ingress
  namespace: techbank
spec:
  rules:
  - host: techbank.local
    http:
      paths:
      - path: /api/v1/accounts
        pathType: Prefix
        backend:
          service:
            name: account-service
            port:
              number: 8001
      - path: /api/v1/transactions
        pathType: Prefix
        backend:
          service:
            name: transaction-service
            port:
              number: 8002
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 8000
