apiVersion: v1
kind: ConfigMap
metadata:
  name: transaction-service-config
  namespace: techbank
data:
  application.properties: |
    spring.application.name=transaction-service
    spring.profiles.active=prod
    server.port=8002
    spring.jpa.hibernate.ddl-auto=update
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.datasource.url=jdbc:postgresql://postgres-service:5432/techbank_transactions
    spring.datasource.username=postgres
    spring.datasource.password=postgres
    spring.datasource.driver-class-name=org.postgresql.Driver
    spring.cloud.kubernetes.discovery.enabled=true
    spring.cloud.kubernetes.config.enabled=true
    logging.level.root=INFO
    logging.level.com.techbank=DEBUG
